name: science
favicon: null
layout_spectrum: 0.9778460008092225
typography_spectrum: 0.2903053166810423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8964507633354515
  lightness: 0.703459161799401
  saturation: 0.30837685568258166
  rhythmicContrast: 0.9473857413977385
purpose: []
